from django.conf.urls import url
from django.contrib import admin

from main.main_content import views


from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [

    url(r'^$', views.main_content, name='main_content'),
    url(r'^index.html?$', views.main_content, name='main_content'),
    url(r'^contacts/?$', views.contact_page, name='contact_page'),
    url(r'^about$',  views.about_us, name='about_us'),
    url(r'^rajony-vyezdov/38-zapravka-kartridzhej-aviamotornaya$',  views.rajony, {'rajony_id': '1' }, name='rajony', ),
    url(r'^rajony-vyezdov/39-zapravka-kartridzhej-avtozavodskaya$', views.rajony, {'rajony_id': '2'}, name='rajony', ),
    url(r'^rajony-vyezdov/40-zapravka-kartridzhej-akademicheskaya$', views.rajony, {'rajony_id': '3'}, name='rajony', ),
    url(r'^rajony-vyezdov/41-zapravka-kartridzhej-aleksandrovskij-sad$', views.rajony, {'rajony_id': '4'}, name='rajony', ),
    url(r'^rajony-vyezdov/43-zapravka-kartridzhej-alekseevskaya$', views.rajony, {'rajony_id': '5'}, name='rajony', ),
    url(r'^rajony-vyezdov/44-zapravka-kartridzhej-altufevo$', views.rajony, {'rajony_id': '6'}, name='rajony', ),
    url(r'^rajony-vyezdov/45-zapravka-kartridzhej-annino$', views.rajony, {'rajony_id': '7'}, name='rajony', ),
    url(r'^rajony-vyezdov/46-zapravka-kartridzhej-arbatskaya$', views.rajony, {'rajony_id': '8'}, name='rajony', ),
    url(r'^rajony-vyezdov/47-zapravka-kartridzhej-metro-aeroport$', views.rajony, {'rajony_id': '9'}, name='rajony', ),
    url(r'^rajony-vyezdov/48-zapravka-kartridzhej-babushkinskaya$', views.rajony, {'rajony_id': '10'}, name='rajony', ),
    url(r'^rajony-vyezdov/49-zapravka-kartridzhej-bagrationovskaya$', views.rajony, {'rajony_id': '11'}, name='rajony', ),
    url(r'^rajony-vyezdov/50-zapravka-kartridzhej-barrikadnaya$', views.rajony, {'rajony_id': '12'}, name='rajony', ),
    url(r'^rajony-vyezdov/51-zapravka-kartridzhej-baumanskaya$', views.rajony, {'rajony_id': '13'}, name='rajony', ),
    url(r'^rajony-vyezdov/52-zapravka-kartridzhej-begovaya$', views.rajony, {'rajony_id': '14'}, name='rajony', ),
    url(r'^rajony-vyezdov/53-zapravka-kartridzhej-belorusskaya$', views.rajony, {'rajony_id': '15'}, name='rajony', ),
    url(r'^rajony-vyezdov/54-zapravka-kartridzhej-belyaevo$', views.rajony, {'rajony_id': '16'}, name='rajony', ),
    url(r'^rajony-vyezdov/55-zapravka-kartridzhej-bibirevo$', views.rajony, {'rajony_id': '17'}, name='rajony', ),
    url(r'^rajony-vyezdov/56-zapravka-kartridzhej-borovickaya$', views.rajony, {'rajony_id': '18'}, name='rajony', ),
    url(r'^rajony-vyezdov/58-zapravka-kartridzhej-botanicheskij-sad$', views.rajony, {'rajony_id': '19'}, name='rajony', ),
    url(r'^rajony-vyezdov/57-zapravka-kartridzhej-bratislavskaya$', views.rajony, {'rajony_id': '20'}, name='rajony', ),
    url(r'^rajony-vyezdov/59-zapravka-kartridzhej-varshavskaya$', views.rajony, {'rajony_id': '21'}, name='rajony', ),
    url(r'^rajony-vyezdov/60-zapravka-kartridzhej-vdnx$', views.rajony, {'rajony_id': '22'}, name='rajony', ),
    url(r'^rajony-vyezdov/61-zapravka-kartridzhej-vladykino$', views.rajony, {'rajony_id': '23'}, name='rajony', ),
    url(r'^rajony-vyezdov/62-zapravka-kartridzhej-vodnyj-stadion$', views.rajony, {'rajony_id': '24'}, name='rajony', ),
    url(r'^rajony-vyezdov/63-zapravka-kartridzhej-vojkovskaya$', views.rajony, {'rajony_id': '25'}, name='rajony', ),
    url(r'^rajony-vyezdov/64-zapravka-kartridzhej-volgogradskij-prospekt$', views.rajony, {'rajony_id': '26'}, name='rajony', ),
    url(r'^rajony-vyezdov/65-zapravka-kartridzhej-volzhskaya$', views.rajony, {'rajony_id': '27'}, name='rajony', ),
    url(r'^rajony-vyezdov/66-zapravka-kartridzhej-vorobevy-gory$', views.rajony, {'rajony_id': '28'}, name='rajony', ),
    url(r'^rajony-vyezdov/68-zapravka-kartridzhej-vystovachnaya$', views.rajony, {'rajony_id': '29'}, name='rajony', ),
    url(r'^rajony-vyezdov/67-zapravka-kartridzhej-vyxino$', views.rajony, {'rajony_id': '30'}, name='rajony', ),
    url(r'^rajony-vyezdov/69-zapravka-kartridzhej-metro-dinamo$', views.rajony, {'rajony_id': '31'}, name='rajony', ),
    url(r'^rajony-vyezdov/70-zapravka-kartridzhej-dmitrovskaya$', views.rajony, {'rajony_id': '32'}, name='rajony', ),
    url(r'^rajony-vyezdov/71-zapravka-kartridzhej-dobryninskaya$', views.rajony, {'rajony_id': '33'}, name='rajony', ),
    url(r'^rajony-vyezdov/72-zapravka-kartridzhej-dubrovka$', views.rajony, {'rajony_id': '34'}, name='rajony', ),
    url(r'^rajony-vyezdov/73-zapravka-kartridzhej-izmajlovskaya$', views.rajony, {'rajony_id': '35'}, name='rajony', ),
    url(r'^rajony-vyezdov/74-zapravka-kartridzhej-kaluzhskaya$', views.rajony, {'rajony_id': '36'}, name='rajony', ),
    url(r'^rajony-vyezdov/75-zapravka-kartridzhej-kantemirovskaya$', views.rajony, {'rajony_id': '37'}, name='rajony', ),
    url(r'^rajony-vyezdov/76-zapravka-kartridzhej-kaxovskaya$', views.rajony, {'rajony_id': '38'}, name='rajony', ),
    url(r'^rajony-vyezdov/77-zapravka-kartridzhej-kashirskaya$', views.rajony, {'rajony_id': '39'}, name='rajony', ),
    url(r'^rajony-vyezdov/78-zapravka-kartridzhej-kievskaya$', views.rajony, {'rajony_id': '40'}, name='rajony', ),
    url(r'^rajony-vyezdov/79-zapravka-kartridzhej-kitaj-gorod$', views.rajony, {'rajony_id': '41'}, name='rajony', ),
    url(r'^rajony-vyezdov/80-zapravka-kartridzhej-kozhuxovskaya$', views.rajony, {'rajony_id': '42'}, name='rajony', ),
    url(r'^rajony-vyezdov/81-zapravka-kartridzhej-kolomenskaya$', views.rajony, {'rajony_id': '43'}, name='rajony', ),
    url(r'^rajony-vyezdov/82-zapravka-kartridzhej-komsomolskaya$', views.rajony, {'rajony_id': '44'}, name='rajony', ),
    url(r'^rajony-vyezdov/83-zapravka-kartridzhej-konkovo$', views.rajony, {'rajony_id': '45'}, name='rajony', ),
    url(r'^rajony-vyezdov/84-zapravka-kartridzhej-krasnogvardejskaya$', views.rajony, {'rajony_id': '46'}, name='rajony', ),
    url(r'^rajony-vyezdov/85-zapravka-kartridzhej-krasnopresnenskaya$', views.rajony, {'rajony_id': '47'}, name='rajony', ),
    url(r'^rajony-vyezdov/86-zapravka-kartridzhej-krasnoselskaya$', views.rajony, {'rajony_id': '48'}, name='rajony', ),
    url(r'^rajony-vyezdov/87-zapravka-kartridzhej-krasnye-vorota$', views.rajony, {'rajony_id': '49'}, name='rajony', ),
    url(r'^rajony-vyezdov/88-zapravka-kartridzhej-krestyanskaya-zastava$', views.rajony, {'rajony_id': '50'}, name='rajony', ),
    url(r'^rajony-vyezdov/89-zapravka-kartridzhej-kropotkinskaya$', views.rajony, {'rajony_id': '51'}, name='rajony', ),
    url(r'^rajony-vyezdov/90-zapravka-kartridzhej-krylatskoe$', views.rajony, {'rajony_id': '52'}, name='rajony', ),
    url(r'^rajony-vyezdov/91-zapravka-kartridzhej-kuzneckij-most$', views.rajony, {'rajony_id': '53'}, name='rajony', ),
    url(r'^rajony-vyezdov/92-zapravka-kartridzhej-kuzminki$', views.rajony, {'rajony_id': '54'}, name='rajony', ),
    url(r'^rajony-vyezdov/93-zapravka-kartridzhej-kuncevskaya$', views.rajony, {'rajony_id': '55'}, name='rajony', ),
    url(r'^rajony-vyezdov/94-zapravka-kartridzhej-kurskaya$', views.rajony, {'rajony_id': '56'}, name='rajony', ),
    url(r'^rajony-vyezdov/95-zapravka-kartridzhej-kutuzovskaya$', views.rajony, {'rajony_id': '57'}, name='rajony', ),
    url(r'^rajony-vyezdov/96-zapravka-kartridzhej-leninskij-prospekt$', views.rajony, {'rajony_id': '58'}, name='rajony', ),
    url(r'^rajony-vyezdov/97-zapravka-kartridzhej-lubyanka$', views.rajony, {'rajony_id': '59'}, name='rajony', ),
    url(r'^rajony-vyezdov/98-zapravka-kartridzhej-lublino$', views.rajony, {'rajony_id': '60'}, name='rajony', ),
    url(r'^rajony-vyezdov/99-zapravka-kartridzhej-marksistskaya$', views.rajony, {'rajony_id': '61'}, name='rajony', ),
    url(r'^rajony-vyezdov/100-zapravka-kartridzhej-marino$', views.rajony, {'rajony_id': '62'}, name='rajony', ),

    url(r'^rajony-vyezdov/101-zapravka-kartridzhej-mayakovskaya$', views.rajony, {'rajony_id': '63'}, name='rajony', ),
    url(r'^rajony-vyezdov/102-zapravka-kartridzhej-medvedkovo$', views.rajony, {'rajony_id': '64'}, name='rajony', ),
    url(r'^rajony-vyezdov/103-zapravka-kartridzhej-mendeleevskaya$', views.rajony, {'rajony_id': '65'}, name='rajony', ),
    url(r'^rajony-vyezdov/104-zapravka-kartridzhej-molodezhnaya$', views.rajony, {'rajony_id': '66'}, name='rajony', ),
    url(r'^rajony-vyezdov/105-zapravka-kartridzhej-nagatinskaya$', views.rajony, {'rajony_id': '67'}, name='rajony', ),
    url(r'^rajony-vyezdov/106-zapravka-kartridzhej-nagornaya$', views.rajony, {'rajony_id': '68'}, name='rajony', ),
    url(r'^rajony-vyezdov/107-zapravka-kartridzhej-naximovskij-prospekt$', views.rajony, {'rajony_id': '69'}, name='rajony', ),
    url(r'^rajony-vyezdov/108-zapravka-kartridzhej-novogireevo$', views.rajony, {'rajony_id': '70'}, name='rajony', ),
    url(r'^rajony-vyezdov/109-zapravka-kartridzhej-novoslobodskaya$', views.rajony, {'rajony_id': '71'}, name='rajony', ),
    url(r'^rajony-vyezdov/110-zapravka-kartridzhej-novye-cheremushki$', views.rajony, {'rajony_id': '72'}, name='rajony', ),
    url(r'^rajony-vyezdov/111-zapravka-kartridzhej-oktyabrskaya$', views.rajony, {'rajony_id': '73'}, name='rajony', ),
    url(r'^rajony-vyezdov/112-zapravka-kartridzhej-oktyabrskoe-pole$', views.rajony, {'rajony_id': '74'}, name='rajony', ),
    url(r'^rajony-vyezdov/113-zapravka-kartridzhej-orexovo$', views.rajony, {'rajony_id': '75'}, name='rajony', ),
    url(r'^rajony-vyezdov/114-zapravka-kartridzhej-otradnoe$', views.rajony, {'rajony_id': '76'}, name='rajony', ),
    url(r'^rajony-vyezdov/115-zapravka-kartridzhej-oxotnyj-ryad$', views.rajony, {'rajony_id': '77'}, name='rajony', ),
    url(r'^rajony-vyezdov/116-zapravka-kartridzhej-metro-paveleckaya$', views.rajony, {'rajony_id': '78'}, name='rajony', ),
    url(r'^rajony-vyezdov/117-zapravka-kartridzhej-park-kultury$', views.rajony, {'rajony_id': '79'}, name='rajony', ),
    url(r'^rajony-vyezdov/118-zapravka-kartridzhej-park-pobedy$', views.rajony, {'rajony_id': '80'}, name='rajony', ),
    url(r'^rajony-vyezdov/119-zapravka-kartridzhej-partizanskaya$', views.rajony, {'rajony_id': '81'}, name='rajony', ),
    url(r'^rajony-vyezdov/120-zapravka-kartridzhej-pervomajskaya$', views.rajony, {'rajony_id': '82'}, name='rajony', ),
    url(r'^rajony-vyezdov/121-zapravka-kartridzhej-perovo$', views.rajony, {'rajony_id': '83'}, name='rajony', ),
    url(r'^rajony-vyezdov/122-zapravka-kartridzhej-petrovsko-razumovskaya$', views.rajony, {'rajony_id': '84'}, name='rajony', ),
    url(r'^rajony-vyezdov/123-zapravka-kartridzhej-pechatniki$', views.rajony, {'rajony_id': '85'}, name='rajony', ),
    url(r'^rajony-vyezdov/124-zapravka-kartridzhej-metro-pionerskaya$', views.rajony, {'rajony_id': '86'}, name='rajony', ),
    url(r'^rajony-vyezdov/125-zapravka-kartridzhej-planernaya$', views.rajony, {'rajony_id': '87'}, name='rajony', ),
    url(r'^rajony-vyezdov/126-zapravka-kartridzhej-ploshad-ilicha$', views.rajony, {'rajony_id': '88'}, name='rajony', ),
    url(r'^rajony-vyezdov/127-zapravka-kartridzhej-ploshad-revolucii$', views.rajony, {'rajony_id': '89'}, name='rajony', ),
    url(r'^rajony-vyezdov/128-zapravka-kartridzhej-polezhaevskaya$', views.rajony, {'rajony_id': '90'}, name='rajony', ),
    url(r'^rajony-vyezdov/129-zapravka-kartridzhej-polyanka$', views.rajony, {'rajony_id': '91'}, name='rajony', ),
    url(r'^rajony-vyezdov/130-zapravka-kartridzhej-prazhskaya$', views.rajony, {'rajony_id': '92'}, name='rajony', ),
    url(r'^rajony-vyezdov/131-zapravka-kartridzhej-preobrazhenskaya-ploshad$', views.rajony, {'rajony_id': '93'}, name='rajony', ),
    url(r'^rajony-vyezdov/132-zapravka-kartridzhej-proletarskaya$', views.rajony, {'rajony_id': '94'}, name='rajony', ),
    url(r'^rajony-vyezdov/133-zapravka-kartridzhej-prospekt-vernadskogo$', views.rajony, {'rajony_id': '95'}, name='rajony', ),
    url(r'^rajony-vyezdov/134-zapravka-kartridzhej-prospekt-mira$', views.rajony, {'rajony_id': '96'}, name='rajony', ),
    url(r'^rajony-vyezdov/135-zapravka-kartridzhej-profsouznaya$', views.rajony, {'rajony_id': '97'}, name='rajony', ),
    url(r'^rajony-vyezdov/136-zapravka-kartridzhej-pushkinskaya$', views.rajony, {'rajony_id': '98'}, name='rajony', ),
    url(r'^rajony-vyezdov/137-zapravka-kartridzhej-rechnoj-vokzal$', views.rajony, {'rajony_id': '99'}, name='rajony', ),
    url(r'^rajony-vyezdov/138-zapravka-kartridzhej-rizhskaya$', views.rajony, {'rajony_id': '100'}, name='rajony', ),
    url(r'^rajony-vyezdov/139-zapravka-kartridzhej-rimskaya$', views.rajony, {'rajony_id': '101'}, name='rajony', ),
    url(r'^rajony-vyezdov/140-zapravka-kartridzhej-ryazanskij-prospekt$', views.rajony, {'rajony_id': '102'}, name='rajony', ),
    url(r'^rajony-vyezdov/141-zapravka-kartridzhej-savelovskaya$', views.rajony, {'rajony_id': '103'}, name='rajony', ),
    url(r'^rajony-vyezdov/142-zapravka-kartridzhej-sviblovo$', views.rajony, {'rajony_id': '104'}, name='rajony', ),
    url(r'^rajony-vyezdov/143-zapravka-kartridzhej-sevastopolskaya$', views.rajony, {'rajony_id': '105'}, name='rajony', ),
    url(r'^rajony-vyezdov/144-zapravka-kartridzhej-semenovskaya$', views.rajony, {'rajony_id': '106'}, name='rajony', ),
    url(r'^rajony-vyezdov/145-zapravka-kartridzhej-serpuxovskaya$', views.rajony, {'rajony_id': '107'}, name='rajony', ),
    url(r'^rajony-vyezdov/146-zapravka-kartridzhej-smolenskaya$', views.rajony, {'rajony_id': '108'}, name='rajony', ),
    url(r'^rajony-vyezdov/147-zapravka-kartridzhej-sokol$', views.rajony, {'rajony_id': '109'}, name='rajony', ),
    url(r'^rajony-vyezdov/148-zapravka-kartridzhej-sokolniki$', views.rajony, {'rajony_id': '110'}, name='rajony', ),
    url(r'^rajony-vyezdov/149-zapravka-kartridzhej-sportivnaya$', views.rajony, {'rajony_id': '111'}, name='rajony', ),
    url(r'^rajony-vyezdov/150-zapravka-kartridzhej-studencheskaya$', views.rajony, {'rajony_id': '112'}, name='rajony', ),
    url(r'^rajony-vyezdov/151-zapravka-kartridzhej-suxarevskaya$', views.rajony, {'rajony_id': '113'}, name='rajony', ),
    url(r'^rajony-vyezdov/152-zapravka-kartridzhej-sxodnenskaya$', views.rajony, {'rajony_id': '114'}, name='rajony', ),
    url(r'^rajony-vyezdov/153-zapravka-kartridzhej-taganskaya$', views.rajony, {'rajony_id': '115'}, name='rajony', ),
    url(r'^rajony-vyezdov/154-zapravka-kartridzhej-tverskaya$', views.rajony, {'rajony_id': '116'}, name='rajony', ),
    url(r'^rajony-vyezdov/155-zapravka-kartridzhej-teatralnaya$', views.rajony, {'rajony_id': '117'}, name='rajony', ),
    url(r'^rajony-vyezdov/156-zapravka-kartridzhej-tekstilshiki$', views.rajony, {'rajony_id': '118'}, name='rajony', ),
    url(r'^rajony-vyezdov/157-zapravka-kartridzhej-timiryazevskaya$', views.rajony, {'rajony_id': '119'}, name='rajony', ),
    url(r'^rajony-vyezdov/158-zapravka-kartridzhej-tretyakovskaya$', views.rajony, {'rajony_id': '120'}, name='rajony', ),
    url(r'^rajony-vyezdov/159-zapravka-kartridzhej-tulskaya$', views.rajony, {'rajony_id': '121'}, name='rajony', ),
    url(r'^rajony-vyezdov/160-zapravka-kartridzhej-turgenevskaya$', views.rajony, {'rajony_id': '122'}, name='rajony', ),
    url(r'^rajony-vyezdov/161-zapravka-kartridzhej-tushinskaya$', views.rajony, {'rajony_id': '123'}, name='rajony', ),
    url(r'^rajony-vyezdov/162-zapravka-kartridzhej-ulica-1905-goda$', views.rajony, {'rajony_id': '124'}, name='rajony', ),
    url(r'^rajony-vyezdov/163-zapravka-kartridzhej-ulica-akademika-yangelya$', views.rajony, {'rajony_id': '125'}, name='rajony', ),
    url(r'^rajony-vyezdov/164-zapravka-kartridzhej-ulica-podbelskogo$', views.rajony, {'rajony_id': '126'}, name='rajony', ),
    url(r'^rajony-vyezdov/165-zapravka-kartridzhej-universitet$', views.rajony, {'rajony_id': '127'}, name='rajony', ),
    url(r'^rajony-vyezdov/166-zapravka-kartridzhej-filevskij-park$', views.rajony, {'rajony_id': '128'}, name='rajony', ),
    url(r'^rajony-vyezdov/167-zapravka-kartridzhej-fili$', views.rajony, {'rajony_id': '129'}, name='rajony', ),
    url(r'^rajony-vyezdov//168-zapravka-kartridzhej-frunzenskaya$', views.rajony, {'rajony_id': '130'}, name='rajony', ),
    url(r'^rajony-vyezdov/169-zapravka-kartridzhej-caricyno$', views.rajony, {'rajony_id': '131'}, name='rajony', ),
    url(r'^rajony-vyezdov/170-zapravka-kartridzhej-cvetnoj-bulvar$', views.rajony, {'rajony_id': '132'}, name='rajony', ),
    url(r'^rajony-vyezdov/171-zapravka-kartridzhej-cherkizovskaya$', views.rajony, {'rajony_id': '133'}, name='rajony', ),
    url(r'^rajony-vyezdov/172-zapravka-kartridzhej-metro-chertanovskaya$', views.rajony, {'rajony_id': '134'}, name='rajony', ),
    url(r'^rajony-vyezdov/173-zapravka-kartridzhej-chexovskaya$', views.rajony, {'rajony_id': '135'}, name='rajony', ),
    url(r'^rajony-vyezdov/174-zapravka-kartridzhej-chistye-prudy$', views.rajony, {'rajony_id': '136'}, name='rajony', ),
    url(r'^rajony-vyezdov/175-zapravka-kartridzhej-chkalovskaya$', views.rajony, {'rajony_id': '137'}, name='rajony', ),
    url(r'^rajony-vyezdov/176-zapravka-kartridzhej-shabolovskaya$', views.rajony, {'rajony_id': '138'}, name='rajony', ),
    url(r'^rajony-vyezdov/177-zapravka-kartridzhej-shosse-entuziastov$', views.rajony, {'rajony_id': '139'}, name='rajony', ),
    url(r'^rajony-vyezdov/178-zapravka-kartridzhej-shelkovskaya$', views.rajony, {'rajony_id': '140'}, name='rajony', ),
    url(r'^rajony-vyezdov/179-zapravka-kartridzhej-shukinskaya$', views.rajony, {'rajony_id': '141'}, name='rajony', ),
    url(r'^rajony-vyezdov/181-zapravka-kartridzhej-ugo-zapadnaya$', views.rajony, {'rajony_id': '142'}, name='rajony', ),
    url(r'^rajony-vyezdov/182-zapravka-kartridzhej-uzhnaya$', views.rajony, {'rajony_id': '143'}, name='rajony', ),

]


urlpatterns += staticfiles_urlpatterns()













